### ISSUE TITLE
Custom scenario bug

### ISSUE THREAD

**Issue by msarofim** [JGCRI/hectorui#56]
Submitter: Marcus C Sarofim

**Describe the bug**
Hector UI crashes whenever a custom scenario is loaded. 

**To Reproduce**
1. Go to https://jgcri.shinyapps.io/HectorUI/
2. Download an RCP template 
3. Choose that template as a custom emissions file
4. See "Custom Scenario Error" (screenshot below)

**Expected behavior**
N/A

**Screenshots**
![image](https://user-images.githubusercontent.com/23127290/193924034-229e9c67-7674-4879-8655-fdaec0fbfab6.png)

**Desktop (please complete the following information):**
I've duplicated this error on both a Windows machine and a Macintosh, and on Chrome, Safari, and Firefox, using both modified and un-modified templates, and a colleague duplicated it on their machine as well. 

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by TSun-climdyn** [comment]
This bug is still there. Can't use custom scenarios.

**Comment by stephpenn1** [comment]
Hi @msarofim and @TSun-climdyn, thank you for your patience on this issue. We found a bug in the template files where certain emission columns are no longer in Hector. Below are links to temporarily fix this bug, please use these templates instead of the downloadable ones in the app. _Note_ we are also working on a new version of the app to be compatible with Hector v3 that will formally fix this bug and update to SSPs.

[RCP26_custom_template_fixed.csv](https://github.com/JGCRI/hectorui/files/15310582/RCP26_custom_template_fixed.csv)
[RCP45_custom_template_fixed.csv](https://github.com/JGCRI/hectorui/files/15310585/RCP45_custom_template_fixed.csv)
[RCP6_custom_template_fixed.csv](https://github.com/JGCRI/hectorui/files/15310587/RCP6_custom_template_fixed.csv)
[RCP85_custom_template_fixed.csv](https://github.com/JGCRI/hectorui/files/15310588/RCP85_custom_template_fixed.csv)
