### ISSUE TITLE
Beta feedback

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hectorui#73]
Hi @stephpenn1 after playing around with the beta, here are some thoughts-

* "Include permafrost thaw:" is in a smaller size font than the other entries ("Select SSPs: ", "Select dates:", etc) -- visually a little confusing
* When I change the "Output Variable", two things: (1) do I need to click "Load Graphs" again? It seems like the graph should auto-update when I change the variable, but it's not. (2) Why does the model re-run? If I've just changed the output variable, shouldn't you be able to instantly load it, instead of re-running?
* When downloading parameters (cool!), probably better to put each parameter on its own line -- easier to see, and parse
* The "Carbon tracking" tab just sat there with its very cool progress indicator...but nothing ever came up
* From the home page, it's slightly confusing that "Explore Hector" and "Run Hector" buttons take you to the same place. Maybe use consistent language?

All this said...overall it looks GREAT. Love the cool, clean design; helpful tooltips; and thoughtful layout. Nice job! 👏

**Comment by stephpenn1** [comment]
Hi @bpbond, thanks for the look through! 
- Good point about changing parameters, we will look into making that an auto-update
- The graphs on the Carbon Tracking tab take quite a bit of time to load because one of them is a gif. I've tried to add the progress bars using `incProgress` as we've used in the past, but it doesn't seem to correlate to the server-side processing exactly. I think the temp fix here is to put some wording to let users know, and try to figure out the loading bar.
